return {
	general = {
		structure = { '"""', "", '"""' },
		direction = false,
		title_pos = 2,
		title_gap = true,
		title_gap_text = "",
		section_gap = false,
		section_gap_text = "",
		section_underline = "",
		section_title_gap = false,
		item_gap = false,
		section_order = { "attrs" },
		include_class_body_attrs = true,
		include_instance_attrs = true,
		include_only_constructor_instance_attrs = true,
	},
	attrs = {
		title = "Attributes:",
		inline = true,
		indent = true,
		include_type = true,
		type_first = false,
		name_kw = "",
		type_kw = "",
		name_wrapper = { "", "" },
		type_wrapper = { "(", "):" },
		is_type_below_name_first = false,
	},
}
