return {
	general = {
		structure = { '"""', "", '"""' },
		direction = false,
		title_pos = 2,
		title_gap = true,
		title_gap_text = "",
		section_gap = false,
		section_gap_text = "",
		section_underline = "",
		section_title_gap = false,
		item_gap = false,
		section_order = { "attrs" },
	},
	attrs = {
		title = "",
		include_class_attrs = true,
		include_instance_attrs = true,
		include_only_constructor_instance_attrs = true,
		inline = false,
		indent = false,
		include_type = true,
		type_first = false,
		name_kw = ":var",
		type_kw = ":vartype",
		name_wrapper = { "", ":" },
		type_wrapper = { "", "" },
		is_type_below_name_first = true,
	},
}
