return {
	general = {
		struct = { "/**", " * ", " */" },
		direction = true,
		title_pos = 2,
		title_gap = true,
		section_gap = false,
		section_underline = "",
		section_title_gap = false,
		item_gap = false,
		section_order = { "params", "return_type" },
	},
	params = {
		title = "",
		inline = true,
		indent = false,
		include_type = false,
		type_first = false,
		name_kw = "@param",
		type_kw = "",
		name_wrapper = { "", "" },
		type_wrapper = { "", "" },
		is_type_below_name_first = false,
	},
	return_type = {
		title = "",
		inline = true,
		indent = false,
		include_type = false,
		type_first = false,
		name_kw = "",
		type_kw = "@return",
		name_wrapper = { "", "" },
		type_wrapper = { "", "" },
		is_type_below_name_first = false,
	},
}
