return {
	general = {
		structure = { '"""', "", '"""' },
		direction = false,
		title_pos = 2,
		title_gap = true,
		title_gap_text = "",
		section_gap = false,
		section_gap_text = "",
		section_underline = "",
		section_title_gap = false,
		item_gap = false,
		section_order = { "params", "return_type" },
	},
	params = {
		title = "Args:",
		inline = true,
		indent = true,
		include_type = true,
		type_first = false,
		name_kw = "",
		type_kw = "",
		name_wrapper = { "", "" },
		type_wrapper = { "(", "):" },
		is_type_below_name_first = false,
	},
	return_type = {
		title = "Returns:",
		inline = true,
		indent = true,
		include_type = true,
		type_first = false,
		name_kw = "",
		type_kw = "",
		name_wrapper = { "", "" },
		type_wrapper = { "", ":" },
		is_type_below_name_first = false,
	},
}
