return {
	general = {
		structure = { '"""', "", '"""' },
		direction = false,
		title_pos = 2,
		title_gap = true,
		section_gap = false,
		section_underline = "",
		section_title_gap = false,
		item_gap = false,
		section_order = { "params", "return_type" },
	},
	params = {
		title = "",
		inline = false,
		indent = false,
		include_type = true,
		type_first = false,
		name_kw = ":param",
		type_kw = ":type",
		name_wrapper = { "", ":" },
		type_wrapper = { "", "" },
		is_type_below_name_first = true,
	},
	return_type = {
		title = "",
		inline = false,
		indent = false,
		include_type = true,
		type_first = false,
		name_kw = ":return:",
		type_kw = ":rtype:",
		name_wrapper = { "", "" },
		type_wrapper = { "", "" },
		is_type_below_name_first = true,
	},
}
