return {
	general = {
		structure = { "///", "///" },
		direction = true,
		title_pos = 1,
		title_gap = true,
		section_gap = true,
		section_underline = "",
		section_title_gap = true,
		item_gap = false,
		section_order = { "params", "return_type" },
	},
	params = {
		title = " # Arguments",
		inline = true,
		indent = false,
		include_type = false,
		type_first = false,
		name_kw = "",
		type_kw = "",
		name_wrapper = { " * `", "`" },
		type_wrapper = { "", "" },
		is_type_below_name_first = false,
	},
	return_type = {
		title = " # Returns",
		inline = true,
		indent = false,
		include_type = false,
		type_first = false,
		name_kw = "",
		type_kw = "",
		name_wrapper = { "", "" },
		type_wrapper = { "", "" },
		is_type_below_name_first = false,
	},
}
