name: Format Check

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  format-check:
    name: Check formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Codedocs Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache StyLua
        uses: actions/cache@v3
        with:
          path: /usr/local/bin/stylua
          key: stylua-v2.0.2

      - name: Install StyLua (if not cached)
        run: |
          if [ ! -f /usr/local/bin/stylua ]; then
            sudo apt update
            sudo apt install -y stylua=2.0.2
          fi
      
      - name: Check Formatting
        run: |
          if [ "$GITHUB_EVENT_NAME" = "push" ]; then
              commit_range="${{ github.event.before }}..${{ github.sha }}"
          elif [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
              commit_range="origin/${{ github.base_ref }}..HEAD"
          else
              commit_range="HEAD~1..HEAD"
          fi

          modified_files=$(git diff --name-only $commit_range -- '*.lua')

          if [ -n "$modified_files" ]; then
              echo "Checking formatting for the following files:"
              echo "$modified_files"
              stylua --check $modified_files
          else
              echo "No Lua files were modified. Skipping formatting check."
          fi
