return {
	comment = {
		{
			structure = {
				"",
			},
			cursor_pos = 1,
			expected_annotation = {
				Google = {
					"# ${1:description}",
				},
				Numpy = {
					"# ${1:description}",
				},
				reST = {
					"# ${1:description}",
				},
			},
		},
	},
	func = {
		{
			structure = {
				"def foo():",
				"	a + b",
			},
			cursor_pos = 1,
			expected_annotation = {
				Google = {
					'	"""',
					"	${1:title}",
					'	"""',
				},
				Numpy = {
					'	"""',
					"	${1:title}",
					'	"""',
				},
				reST = {
					'	"""',
					"	${1:title}",
					'	"""',
				},
			},
		},
		{
			structure = {
				"def foo() -> int:",
				"	a + b",
			},
			cursor_pos = 1,
			expected_annotation = {
				Google = {
					'	"""',
					"	${1:title}",
					"",
					"	Returns:",
					"		${2:int}: ${3:description}",
					'	"""',
				},
				Numpy = {
					'	"""',
					"	${1:title}",
					"",
					"	Returns",
					"	-------",
					"	${2:int}",
					"		${3:description}",
					'	"""',
				},
				reST = {
					'	"""',
					"	${1:title}",
					"",
					"	:return: ${2:description}",
					"	:rtype: ${3:int}",
					'	"""',
				},
			},
		},
		{
			structure = {
				"def foo(a, b):",
				"	a + b",
			},
			cursor_pos = 1,
			expected_annotation = {
				Google = {
					'	"""',
					"	${1:title}",
					"",
					"	Args:",
					"		a (${2:}): ${3:description}",
					"		b (${4:}): ${5:description}",
					'	"""',
				},
				Numpy = {
					'	"""',
					"	${1:title}",
					"",
					"	Parameters",
					"	----------",
					"	a: ${2:}",
					"		${3:description}",
					"	b: ${4:}",
					"		${5:description}",
					'	"""',
				},
				reST = {
					'	"""',
					"	${1:title}",
					"",
					"	:param a: ${2:description}",
					"	:type a: ${3:}",
					"	:param b: ${4:description}",
					"	:type b: ${5:}",
					'	"""',
				},
			},
		},
		{
			structure = {
				"def foo(a, b) -> int:",
				"	a + b",
			},
			cursor_pos = 1,
			expected_annotation = {
				Google = {
					'	"""',
					"	${1:title}",
					"",
					"	Args:",
					"		a (${2:}): ${3:description}",
					"		b (${4:}): ${5:description}",
					"",
					"	Returns:",
					"		${6:int}: ${7:description}",
					'	"""',
				},
				Numpy = {
					'	"""',
					"	${1:title}",
					"",
					"	Parameters",
					"	----------",
					"	a: ${2:}",
					"		${3:description}",
					"	b: ${4:}",
					"		${5:description}",
					"",
					"	Returns",
					"	-------",
					"	${6:int}",
					"		${7:description}",
					'	"""',
				},
				reST = {
					'	"""',
					"	${1:title}",
					"",
					"	:param a: ${2:description}",
					"	:type a: ${3:}",
					"	:param b: ${4:description}",
					"	:type b: ${5:}",
					"	:return: ${6:description}",
					"	:rtype: ${7:int}",
					'	"""',
				},
			},
		},
		{
			structure = {
				"def foo(a: int, b: int):",
				"	a + b",
			},
			cursor_pos = 1,
			expected_annotation = {
				Google = {
					'	"""',
					"	${1:title}",
					"",
					"	Args:",
					"		a (${2:int}): ${3:description}",
					"		b (${4:int}): ${5:description}",
					'	"""',
				},
				Numpy = {
					'	"""',
					"	${1:title}",
					"",
					"	Parameters",
					"	----------",
					"	a: ${2:int}",
					"		${3:description}",
					"	b: ${4:int}",
					"		${5:description}",
					'	"""',
				},
				reST = {
					'	"""',
					"	${1:title}",
					"",
					"	:param a: ${2:description}",
					"	:type a: ${3:int}",
					"	:param b: ${4:description}",
					"	:type b: ${5:int}",
					'	"""',
				},
			},
		},
		{
			structure = {
				"def foo(a: int, b: int) -> int:",
				"	a + b",
			},
			cursor_pos = 1,
			expected_annotation = {
				Google = {
					'	"""',
					"	${1:title}",
					"",
					"	Args:",
					"		a (${2:int}): ${3:description}",
					"		b (${4:int}): ${5:description}",
					"",
					"	Returns:",
					"		${6:int}: ${7:description}",
					'	"""',
				},
				Numpy = {
					'	"""',
					"	${1:title}",
					"",
					"	Parameters",
					"	----------",
					"	a: ${2:int}",
					"		${3:description}",
					"	b: ${4:int}",
					"		${5:description}",
					"",
					"	Returns",
					"	-------",
					"	${6:int}",
					"		${7:description}",
					'	"""',
				},
				reST = {
					'	"""',
					"	${1:title}",
					"",
					"	:param a: ${2:description}",
					"	:type a: ${3:int}",
					"	:param b: ${4:description}",
					"	:type b: ${5:int}",
					"	:return: ${6:description}",
					"	:rtype: ${7:int}",
					'	"""',
				},
			},
		},
		{
			structure = {
				"def foo(a, b, c: int):",
				"	a + b",
			},
			cursor_pos = 1,
			expected_annotation = {
				Google = {
					'	"""',
					"	${1:title}",
					"",
					"	Args:",
					"		a (${2:}): ${3:description}",
					"		b (${4:}): ${5:description}",
					"		c (${6:int}): ${7:description}",
					'	"""',
				},
				Numpy = {
					'	"""',
					"	${1:title}",
					"",
					"	Parameters",
					"	----------",
					"	a: ${2:}",
					"		${3:description}",
					"	b: ${4:}",
					"		${5:description}",
					"	c: ${6:int}",
					"		${7:description}",
					'	"""',
				},
				reST = {
					'	"""',
					"	${1:title}",
					"",
					"	:param a: ${2:description}",
					"	:type a: ${3:}",
					"	:param b: ${4:description}",
					"	:type b: ${5:}",
					"	:param c: ${6:description}",
					"	:type c: ${7:int}",
					'	"""',
				},
			},
		},
		{
			structure = {
				"def foo(a, b: int, c):",
				"	a + b",
			},
			cursor_pos = 1,
			expected_annotation = {
				Google = {
					'	"""',
					"	${1:title}",
					"",
					"	Args:",
					"		a (${2:}): ${3:description}",
					"		b (${4:int}): ${5:description}",
					"		c (${6:}): ${7:description}",
					'	"""',
				},
				Numpy = {
					'	"""',
					"	${1:title}",
					"",
					"	Parameters",
					"	----------",
					"	a: ${2:}",
					"		${3:description}",
					"	b: ${4:int}",
					"		${5:description}",
					"	c: ${6:}",
					"		${7:description}",
					'	"""',
				},
				reST = {
					'	"""',
					"	${1:title}",
					"",
					"	:param a: ${2:description}",
					"	:type a: ${3:}",
					"	:param b: ${4:description}",
					"	:type b: ${5:int}",
					"	:param c: ${6:description}",
					"	:type c: ${7:}",
					'	"""',
				},
			},
		},
	},
}
